setwd("C:/ex/R")
getwd()

library("tm")
testText<-readLines("input2.txt")
print(testText)
testText<- VectorSource(testText)
corpus<- Corpus(testText)
corpus<-tm_map(corpus,removePunctuation)
corpus
inspect(corpus)
corpus<- tm_map(corpus,removeNumbers)
corpus <- tm_map(corpus, tolower)
inspect(corpus)
corpus<- tm_map(corpus,removeWords,stopwords("english"))
strwrap(corpus[[1]])
corpus<-tm_map(corpus, PlainTextDocument)
dtm<-DocumentTermMatrix(corpus)
dtm2<-as.matrix(dtm)
frequency<- colSums(dtm2)
frequency<- sort(frequency,decreasing=T)
print(frequency)
frequency[1:5]
barplot(frequency[1:20], las=3)
